### ISSUE TITLE
libgcrypt: POWER AES Vector Acceleration

### ISSUE THREAD

**Issue by edelsohn** [edelsohn/libgcrypt#1]
Use POWER8 and POWER9 ISA enhancements to improve the performance of AES. Demonstrate why achieved performance is close to optimal for the platform. Optimized implementations in the Cryptogams repository[1] may serve as useful references. Financial bounty upon completion and community acceptance of patches.

https://github.com/dot-asm/cryptogams/

This is a proxy for https://dev.gnupg.org/T4529

**Comment by shawnl** [comment]
https://dev.gnupg.org/T4529

**Comment by edelsohn** [comment]
This issue has been closed/resolved upstream in the libgcrypt community, so reflecting that here. The implementation was delivered by combined effort of Jussi and Shawn.
