### ISSUE TITLE
libgcrypt: POWER SHA-2 Vector Acceleration

### ISSUE THREAD

**Issue by edelsohn** [edelsohn/libgcrypt#2]
Use POWER8 and POWER9 ISA enhancements to improve the performance of SHA-2. Demonstrate why achieved performance is close to optimal for the platform. Optimized implementations in the Cryptogams repository[1] may serve as useful references. Financial bounty upon completion and community acceptance of patches.

https://github.com/dot-asm/cryptogams/

This is a proxy for https://dev.gnupg.org/T4530

**Comment by dmiller423** [comment]
I can do Power8,  I don't have access to 9 currently..

**Comment by edelsohn** [comment]
Thanks, but there already is a developer working on the issues.  This is proxy for the issues at the main, GNU PG repository.

**Comment by jkivilin** [comment]
https://dev.gnupg.org/T4530

**Comment by edelsohn** [comment]
This issue has been closed/resolved upstream in the libgcrypt community, so reflecting that here. The implementation was delivered by Jussi.
